### ISSUE TITLE
Add heroku deploy step to CI

### ISSUE THREAD

**Issue by tjwaterman99** [tjwaterman99/getcohorts#15]
It would be great if we could provision a free heroku app, deploy there, run a test suite against it, and then if that passes deploy to the app to `api.getcohorts.com`.

**Comment by tjwaterman99** [comment]
We also need to make sure the free app is destroyed, even if the test suite fails.

```
steps:
  ...
  - name: Teardown Heroku app
    if: ${{ always() }}
```
