### ISSUE TITLE
Add link to Swagger Docs on the docs site

### ISSUE THREAD

**Issue by tjwaterman99** [tjwaterman99/getcohorts#22]
This looks pretty simple. 

```yaml
nav:
    - Introduction: 'index.md'
    - 'about.md'
    - 'Issue Tracker': 'https://example.com/'
```

https://www.mkdocs.org/user-guide/configuration/#documentation-layout
